### ISSUE TITLE
SPELL for new logs

### ISSUE THREAD

**Issue by danielhanbitlee** [bave/pyspell#2]
@bave I have training log outputs (~4.6 gb) that I converted to spell using your code. I also have new test log outputs (~4.5 gb). Is there a way to use your code to take one log each from the test data and use the SPELL from the training data to convert each log in test data into SPELL?

Another way is to combine training logs and test logs together into one file and run SPELL together. However, this takes too much time. And I think in a live-streaming setting where each new log is generated one at a time, it's appropriate to use previous SPELL outputs to convert the new log into SPELL to generate a log key.

Any help would be appreciated.

**Comment by bave** [comment]
Is your question shown in the test-dir sample?
