### ISSUE TITLE
how to run the code

### ISSUE THREAD

**Issue by yip522364642** [bave/pyspell#3]
i have no idea that how to run these code correctly? could u please explain how to do in detail? Thank u very much

**Comment by bave** [comment]
Is the information presented in the test-dir sample insufficient?

**Comment by yip522364642** [comment]
> Is the information presented in the test-dir sample insufficient?

I wonder if this code can be run on Windows? thanks

**Comment by bave** [comment]
I check the code by running it on linux or macos. If you run it on windows, why not use WSL?

**Comment by yip522364642** [comment]
> I check the code by running on linux or macos.
> I check the code by running it on linux or macos. If you run it on windows, why not use WSL?

thanks for your help. I will try it
